source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'pg'
gem 'jquery-rails'
gem 'font-awesome-sass-rails'
gem 'twitter-bootstrap-rails'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
	gem 'pry-rails'
	gem 'pry-debugger'
	gem 'pry-stack_explorer'
	gem 'better_errors'
	gem 'quiet_assets'
	gem 'binding_of_caller'
	gem 'meta_request'
	gem 'annotate'
end
#the groups dictate what stage of production/development the gems are used for